// Liste officielle des 127 voitures de Need for Speed Heat (33 constructeurs).
// Source : EA / "Under the Hood — NFS Heat Car List".
const CARS = [
  { brand: "Acura", model: "NSX", year: 2017, cat: "Sportscar" },
  { brand: "Acura", model: "RSX-S", year: 2004, cat: "Coupe" },
  { brand: "Alfa Romeo", model: "Giulia Quadrifoglio", year: 2016, cat: "Performance" },
  { brand: "Aston Martin", model: "DB5", year: 1964, cat: "Classic" },
  { brand: "Aston Martin", model: "DB11", year: 2017, cat: "Sportscar" },
  { brand: "Aston Martin", model: "Vulcan", year: 2016, cat: "Hypercar" },
  { brand: "Audi", model: "R8 V10 Performance Coupé", year: 2019, cat: "Supercar" },
  { brand: "Audi", model: "S5 Sportback", year: 2017, cat: "Performance" },
  { brand: "BMW", model: "i8 Roadster", year: 2018, cat: "Open-top" },
  { brand: "BMW", model: "Z4 M40i", year: 2020, cat: "Open-top" },
  { brand: "BMW", model: "M4", year: 2018, cat: "Performance" },
  { brand: "BMW", model: "M2 Competition", year: 2019, cat: "Performance" },
  { brand: "BMW", model: "M4 GTS", year: 2016, cat: "Performance" },
  { brand: "BMW", model: "M3 E46 GTR", year: 2006, cat: "Coupe" },
  { brand: "BMW", model: "M4 Cabriolet", year: 2018, cat: "Open-top" },
  { brand: "BMW", model: "i8 Coupé", year: 2018, cat: "Sportscar" },
  { brand: "BMW", model: "M3", year: 2006, cat: "Performance" },
  { brand: "BMW", model: "M3 Evolution II", year: 1988, cat: "Performance" },
  { brand: "BMW", model: "M3", year: 2010, cat: "Performance" },
  { brand: "BMW", model: "M5", year: 2018, cat: "Performance" },
  { brand: "BMW", model: "X6 M", year: 2016, cat: "SUV" },
  { brand: "Buick", model: "Grand National", year: 1987, cat: "Muscle" },
  { brand: "Chevrolet", model: "Corvette ZR1 Coupé", year: 2019, cat: "Sportscar" },
  { brand: "Chevrolet", model: "Corvette Grand Sport", year: 2017, cat: "Sportscar" },
  { brand: "Chevrolet", model: "Camaro SS", year: 1967, cat: "Classic" },
  { brand: "Chevrolet", model: "Colorado ZR2", year: 2017, cat: "Pickup" },
  { brand: "Chevrolet", model: "Corvette Z06", year: 2013, cat: "Sportscar" },
  { brand: "Chevrolet", model: "Camaro Z28", year: 2014, cat: "Muscle" },
  { brand: "Chevrolet", model: "Bel Air", year: 1955, cat: "Classic" },
  { brand: "Chevrolet", model: "C10 Stepside Pickup", year: 1965, cat: "Classic" },
  { brand: "Dodge", model: "Challenger SRT8", year: 2014, cat: "Muscle" },
  { brand: "Dodge", model: "Charger", year: 1969, cat: "Classic" },
  { brand: "Ferrari", model: "Testarossa Coupé", year: 1984, cat: "Supercar" },
  { brand: "Ferrari", model: "FXX-K Evo", year: 2018, cat: "Hypercar" },
  { brand: "Ferrari", model: "488 Pista", year: 2019, cat: "Supercar" },
  { brand: "Ferrari", model: "458 Spider", year: 2014, cat: "Supercar" },
  { brand: "Ferrari", model: "458 Italia", year: 2014, cat: "Supercar" },
  { brand: "Ferrari", model: "F40", year: 1988, cat: "Supercar" },
  { brand: "Ferrari", model: "LaFerrari", year: 2016, cat: "Hypercar" },
  { brand: "Ferrari", model: "488 GTB", year: 2015, cat: "Supercar" },
  { brand: "Ford", model: "F-150 Raptor (FEM)", year: 2016, cat: "Pickup" },
  { brand: "Ford", model: "Focus RS", year: 2016, cat: "Hot Hatch" },
  { brand: "Ford", model: "Mustang GT", year: 2015, cat: "Muscle" },
  { brand: "Ford", model: "F-150 Raptor", year: 2016, cat: "Pickup" },
  { brand: "Ford", model: "Mustang", year: 1965, cat: "Classic" },
  { brand: "Ford", model: "Mustang BOSS 302", year: 1969, cat: "Classic" },
  { brand: "Ford", model: "GT", year: 2017, cat: "Supercar" },
  { brand: "Ford", model: "Mustang Foxbody", year: 1990, cat: "Muscle" },
  { brand: "Honda", model: "S2000", year: 2009, cat: "Open-top" },
  { brand: "Honda", model: "NSX Type-R", year: 1992, cat: "Sportscar" },
  { brand: "Honda", model: "Civic Type-R", year: 2000, cat: "Hot Hatch" },
  { brand: "Honda", model: "Civic Type-R", year: 2015, cat: "Hot Hatch" },
  { brand: "Infiniti", model: "Q60S", year: 2017, cat: "Sportscar" },
  { brand: "Jaguar", model: "F-Type R Cabriolet", year: 2019, cat: "Open-top" },
  { brand: "Jaguar", model: "F-Type R Coupé", year: 2017, cat: "Sportscar" },
  { brand: "Koenigsegg", model: "Regera", year: 2016, cat: "Hypercar" },
  { brand: "Lamborghini", model: "Countach 25th Anniversary", year: 1989, cat: "Supercar" },
  { brand: "Lamborghini", model: "Aventador SVJ Coupé", year: 2019, cat: "Supercar" },
  { brand: "Lamborghini", model: "Aventador SVJ Roadster", year: 2019, cat: "Open-top" },
  { brand: "Lamborghini", model: "Huracán Performante", year: 2018, cat: "Supercar" },
  { brand: "Lamborghini", model: "Huracán Performante Spyder", year: 2018, cat: "Open-top" },
  { brand: "Lamborghini", model: "Aventador S", year: 2018, cat: "Open-top" },
  { brand: "Lamborghini", model: "Aventador S Roadster", year: 2018, cat: "Open-top" },
  { brand: "Lamborghini", model: "Huracán Spyder", year: 2018, cat: "Open-top" },
  { brand: "Lamborghini", model: "Huracán", year: 2018, cat: "Supercar" },
  { brand: "Lamborghini", model: "Diablo SV", year: 1995, cat: "Supercar" },
  { brand: "Lamborghini", model: "Murciélago SV", year: 2010, cat: "Supercar" },
  { brand: "Land Rover", model: "Defender 110 Double Cab", year: 2016, cat: "Offroad" },
  { brand: "Land Rover", model: "Range Rover Sport SVR", year: 2015, cat: "SUV" },
  { brand: "Lotus", model: "Exige S", year: 2006, cat: "Trackday" },
  { brand: "Mazda", model: "MX-5", year: 2015, cat: "Open-top" },
  { brand: "Mazda", model: "MX-5", year: 1996, cat: "Open-top" },
  { brand: "Mazda", model: "RX-7 Spirit R", year: 2002, cat: "Coupe" },
  { brand: "McLaren", model: "600LT", year: 2018, cat: "Supercar" },
  { brand: "McLaren", model: "P1 GTR", year: 2015, cat: "Hypercar" },
  { brand: "McLaren", model: "570S Spider", year: 2018, cat: "Open-top" },
  { brand: "McLaren", model: "P1", year: 2015, cat: "Hypercar" },
  { brand: "McLaren", model: "570S", year: 2015, cat: "Supercar" },
  { brand: "Mercedes-AMG", model: "C63 Coupé", year: 2018, cat: "Coupe" },
  { brand: "Mercedes-AMG", model: "GT R", year: 2017, cat: "Sportscar" },
  { brand: "Mercedes-AMG", model: "GT S Roadster", year: 2019, cat: "Open-top" },
  { brand: "Mercedes-AMG", model: "G 63", year: 2017, cat: "SUV" },
  { brand: "Mercedes-AMG", model: "GT", year: 2015, cat: "Sportscar" },
  { brand: "Mercedes-AMG", model: "A 45", year: 2014, cat: "Hot Hatch" },
  { brand: "Mercury", model: "Cougar", year: 1967, cat: "Classic" },
  { brand: "Mini", model: "Countryman JCW", year: 2017, cat: "Hot Hatch" },
  { brand: "Mitsubishi", model: "Lancer Evolution X", year: 2008, cat: "Rally" },
  { brand: "Mitsubishi", model: "Lancer Evolution IX", year: 2007, cat: "Rally" },
  { brand: "Nissan", model: "370Z 50th Anniversary", year: 2018, cat: "Coupe" },
  { brand: "Nissan", model: "GT-R Nismo", year: 2017, cat: "Supercar" },
  { brand: "Nissan", model: "370Z Nismo", year: 2018, cat: "Coupe" },
  { brand: "Nissan", model: "350Z (Rachel's)", year: 2003, cat: "Coupe" },
  { brand: "Nissan", model: "Skyline GT-R (Eddie's)", year: 2002, cat: "Coupe" },
  { brand: "Nissan", model: "GT-R", year: 2017, cat: "Supercar" },
  { brand: "Nissan", model: "180SX Type X", year: 1996, cat: "Coupe" },
  { brand: "Nissan", model: "350Z", year: 2008, cat: "Coupe" },
  { brand: "Nissan", model: "Skyline GT-R V·Spec", year: 1999, cat: "Coupe" },
  { brand: "Nissan", model: "Fairlady 240ZG", year: 1971, cat: "Coupe" },
  { brand: "Nissan", model: "Skyline GT-R V·Spec", year: 1993, cat: "Coupe" },
  { brand: "Nissan", model: "Silvia Spec-R Aero", year: 2002, cat: "Coupe" },
  { brand: "Nissan", model: "Skyline 2000 GT-R", year: 1971, cat: "Coupe" },
  { brand: "Pagani", model: "Huayra BC", year: 2017, cat: "Hypercar" },
  { brand: "Plymouth", model: "Barracuda", year: 1970, cat: "Classic" },
  { brand: "Polestar", model: "Polestar 1", year: 2020, cat: "Coupe" },
  { brand: "Pontiac", model: "Firebird", year: 1977, cat: "Classic" },
  { brand: "Porsche", model: "911 GT3 RS", year: 2019, cat: "Sportscar" },
  { brand: "Porsche", model: "Cayman GT4", year: 2015, cat: "Sportscar" },
  { brand: "Porsche", model: "911 GT2 RS", year: 2018, cat: "Supercar" },
  { brand: "Porsche", model: "911 Carrera GTS", year: 2018, cat: "Sportscar" },
  { brand: "Porsche", model: "911 Carrera GTS Cabriolet", year: 2018, cat: "Open-top" },
  { brand: "Porsche", model: "911 Targa 4 GTS", year: 2018, cat: "Sportscar" },
  { brand: "Porsche", model: "718 Cayman GTS", year: 2018, cat: "Sportscar" },
  { brand: "Porsche", model: "911 Turbo S Exclusive", year: 2018, cat: "Sportscar" },
  { brand: "Porsche", model: "911 Turbo S Exclusive Cab", year: 2018, cat: "Open-top" },
  { brand: "Porsche", model: "911 Carrera RSR 2.8", year: 1973, cat: "Sportscar" },
  { brand: "Porsche", model: "911 Carrera S", year: 1996, cat: "Sportscar" },
  { brand: "Porsche", model: "918 Spyder", year: 2015, cat: "Hypercar" },
  { brand: "Porsche", model: "Panamera Turbo", year: 2017, cat: "Performance" },
  { brand: "SRT", model: "Viper GTS", year: 2014, cat: "Sportscar" },
  { brand: "Subaru", model: "Impreza WRX STI", year: 2006, cat: "Rally" },
  { brand: "Subaru", model: "BRZ Premium", year: 2014, cat: "Coupe" },
  { brand: "Subaru", model: "Impreza WRX STI", year: 2010, cat: "Rally" },
  { brand: "Volkswagen", model: "Coccinelle (Beetle)", year: 1963, cat: "Hot Hatch" },
  { brand: "Volkswagen", model: "Golf GTI Clubsport", year: 2016, cat: "Hot Hatch" },
  { brand: "Volkswagen", model: "Golf GTI", year: 1976, cat: "Hot Hatch" },
  { brand: "Volvo", model: "Amazon P130", year: 1970, cat: "Classic" },
  { brand: "Volvo", model: "242 DL", year: 1975, cat: "Sedan" }
];
